header:
  version: 14
repos:
  poky:
    url: "https://git.yoctoproject.org/git/poky"
    branch: "dunfell"
    layers:
      meta:
      meta-poky:
  meta-osselot:
    url: "https://github.com/iris-GmbH/meta-osselot.git"
    branch: "dunfell"
